name: Python CI/CD Workflow

# Pemicu: Menjalankan workflow pada setiap 'push' ke branch 'main' atau saat ada 'pull request'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    # Menjalankan pada mesin virtual Ubuntu versi terbaru
    runs-on: ubuntu-latest
    strategy:
      # Menguji pada beberapa versi Python untuk memastikan kompatibilitas
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    # Langkah 1: Mengunduh kode dari repositori Anda ke mesin virtual
    - name: Check out repository code
      uses: actions/checkout@v3

    # Langkah 2: Mengatur lingkungan Python sesuai versi dari matrix
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Langkah 3: Menginstal dependensi yang dibutuhkan oleh proyek
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Menginstal toolkit Anda dari pyproject.toml beserta dependensinya
        pip install .
        # Menginstal pytest untuk pengujian
        pip install pytest

    # Langkah 4: Menjalankan unit test
    # Perintah ini akan mencari dan menjalankan semua file tes
    # yang mengikuti konvensi penamaan pytest (misal: test_*.py).
    # Buat file tes Anda untuk membuat langkah ini berguna.
    - name: Run tests with pytest
      run: |
        pytest